/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package golfscorepro.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import golfscorepro.model.GolfClub;
import golfscorepro.model.Golfer;
import golfscorepro.model.UndoStack;
import golfscorepro.view.SearchSortView;
import golfscorepro.model.RecentGolferQueue;




/**
 *
 * @author upadh
 */
public class GolferView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GolferView.class.getName());

    /**
     * Creates new form GolferView
     */
    private void loadGolfersToTable() {
        DefaultTableModel model = (DefaultTableModel) tblGolfers.getModel();
        model.setRowCount(0); // clear table

        for (Golfer g : GolfClub.getGolfers()) {
            Object[] row = { g.getGolferId(), g.getName(), g.getHandicap() };
            model.addRow(row);
        }
    }

    public GolferView() {
        initComponents();
        loadGolfersToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        golferId = new javax.swing.JLabel();
        txtGolferId = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        handicap = new javax.swing.JLabel();
        txtHandicap = new javax.swing.JTextField();
        btnAddGolfer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGolfers = new javax.swing.JTable();
        btnDeleteGolfer = new javax.swing.JButton();
        btnUndoDelete = new javax.swing.JButton();
        btnSearchSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Golfer Management");

        jLabel1.setText("Golfer Management Screen");

        golferId.setText("Golfer ID");

        txtGolferId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGolferIdActionPerformed(evt);
            }
        });

        name.setText("Name");

        handicap.setText("Handicap");

        txtHandicap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHandicapActionPerformed(evt);
            }
        });

        btnAddGolfer.setBackground(new java.awt.Color(27, 94, 32));
        btnAddGolfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddGolfer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddGolfer.setText("Add Golfer");
        btnAddGolfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGolferActionPerformed(evt);
            }
        });

        tblGolfers.setBackground(new java.awt.Color(0, 151, 45));
        tblGolfers.setForeground(new java.awt.Color(255, 255, 255));
        tblGolfers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Golfer ID", "Name", "Handicap"
            }
        ));
        jScrollPane1.setViewportView(tblGolfers);

        btnDeleteGolfer.setBackground(new java.awt.Color(27, 94, 32));
        btnDeleteGolfer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteGolfer.setText("Delete Selected");
        btnDeleteGolfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGolferActionPerformed(evt);
            }
        });

        btnUndoDelete.setBackground(new java.awt.Color(27, 94, 32));
        btnUndoDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnUndoDelete.setText("Undo Delete");
        btnUndoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoDeleteActionPerformed(evt);
            }
        });

        btnSearchSort.setBackground(new java.awt.Color(27, 94, 32));
        btnSearchSort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchSort.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSort.setText("Search and Sort");
        btnSearchSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(handicap)
                                .addGap(47, 47, 47)
                                .addComponent(txtHandicap, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(golferId)
                                    .addComponent(name))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGolferId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAddGolfer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDeleteGolfer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUndoDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(golferId)
                            .addComponent(txtGolferId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(handicap)
                            .addComponent(txtHandicap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddGolfer)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteGolfer)
                            .addComponent(btnUndoDelete))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearchSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGolferIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGolferIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolferIdActionPerformed

    private void txtHandicapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandicapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandicapActionPerformed

    private void btnAddGolferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGolferActionPerformed
        String id = txtGolferId.getText().trim();
        String name = txtName.getText().trim();
        String handicapText = txtHandicap.getText().trim();

        // Basic validation
        if (id.isEmpty() || name.isEmpty() || handicapText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        int handicap;
        try {
            handicap = Integer.parseInt(handicapText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Handicap must be a number.");
            return;
        }

        if (handicap < 0 || handicap > 54) {
            JOptionPane.showMessageDialog(this, "Handicap must be between 0 and 54.");
            return;
        }

        // Duplicate ID check
        for (Golfer g : GolfClub.getGolfers()) {
            if (g.getGolferId().equalsIgnoreCase(id)) {
                JOptionPane.showMessageDialog(this, "Duplicate Golfer ID. Please use a unique ID.");
                return;
            }
        }

        // Save golfer
        Golfer newGolfer = new Golfer(id, name, handicap);
        GolfClub.addGolfer(newGolfer);
        
        RecentGolferQueue.addGolfer(newGolfer);

        // Refresh UI
        loadGolfersToTable();

        // Clear inputs
        txtGolferId.setText("");
        txtName.setText("");
        txtHandicap.setText("");

        JOptionPane.showMessageDialog(this, "Golfer added successfully!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGolferActionPerformed

    private void btnDeleteGolferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGolferActionPerformed
        int selectedRow = tblGolfers.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a golfer to delete.");
        return;
        }

        Golfer removedGolfer = GolfClub.getGolfers().remove(selectedRow);

        // Push to stack for undo
        UndoStack.push(removedGolfer);

        loadGolfersToTable();

        JOptionPane.showMessageDialog(this, "Golfer deleted. You can undo this action.");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGolferActionPerformed

    private void btnUndoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoDeleteActionPerformed
        if (UndoStack.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nothing to undo.");
        return;
        }

        Golfer restoredGolfer = UndoStack.pop();
        GolfClub.addGolfer(restoredGolfer);

        loadGolfersToTable();

        JOptionPane.showMessageDialog(this, "Golfer restored successfully.");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUndoDeleteActionPerformed

    private void btnSearchSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSortActionPerformed
        new SearchSortView().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GolferView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGolfer;
    private javax.swing.JButton btnDeleteGolfer;
    private javax.swing.JButton btnSearchSort;
    private javax.swing.JButton btnUndoDelete;
    private javax.swing.JLabel golferId;
    private javax.swing.JLabel handicap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTable tblGolfers;
    private javax.swing.JTextField txtGolferId;
    private javax.swing.JTextField txtHandicap;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
