/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package golfscorepro.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import golfscorepro.model.GolfClub;
import golfscorepro.model.Round;
import golfscorepro.model.RecentRoundQueue;


/**
 *
 * @author upadh
 */
public class RoundView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoundView.class.getName());

    private void loadRoundsToTable() {
        DefaultTableModel model = (DefaultTableModel) tblRounds.getModel();
        model.setRowCount(0);

        for (Round r : GolfClub.getRounds()) {
            Object[] row = { r.getRoundId(), r.getGolferId(), r.getCourseName(), r.getDate(), r.getTotalScore() };
            model.addRow(row);
        }
    }

    /**
     * Creates new form RoundView
     */
    public RoundView() {
        initComponents();
        loadRoundsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRoundId = new javax.swing.JTextField();
        txtRoundGolferId = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtRoundDate = new javax.swing.JTextField();
        txtTotalScore = new javax.swing.JTextField();
        btnAddRound = new javax.swing.JButton();
        btnDeleteRound = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRounds = new javax.swing.JTable();
        panelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Round Management");

        jLabel1.setText("Round Management Screen");

        jLabel2.setText("Round ID");

        jLabel3.setText("Golfer ID");

        jLabel4.setText("Course Name");

        jLabel5.setText("Date (YYYY-MM-DD)");

        jLabel6.setText("Total Score");

        btnAddRound.setBackground(new java.awt.Color(27, 94, 32));
        btnAddRound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRound.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRound.setText("Add Round");
        btnAddRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoundActionPerformed(evt);
            }
        });

        btnDeleteRound.setBackground(new java.awt.Color(27, 94, 32));
        btnDeleteRound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteRound.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteRound.setText("Delete Selected");
        btnDeleteRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoundActionPerformed(evt);
            }
        });

        tblRounds.setBackground(new java.awt.Color(0, 151, 45));
        tblRounds.setForeground(new java.awt.Color(255, 255, 255));
        tblRounds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Round ID", "Golfer ID", "Course", "Date", "Total Score"
            }
        ));
        jScrollPane1.setViewportView(tblRounds);

        panelHeader.setBackground(new java.awt.Color(27, 94, 32));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnAddRound))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoundDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoundGolferId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoundId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteRound))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRoundId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRoundGolferId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRoundDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRound)
                            .addComponent(btnDeleteRound))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoundActionPerformed
        String roundId = txtRoundId.getText().trim();
        String golferId = txtRoundGolferId.getText().trim();
        String course = txtCourseName.getText().trim();
        String date = txtRoundDate.getText().trim();
        String scoreText = txtTotalScore.getText().trim();

        if (roundId.isEmpty() || golferId.isEmpty() || course.isEmpty() || date.isEmpty() || scoreText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Date must be in YYYY-MM-DD format.");
            return;
        }

        int score;
        try {
            score = Integer.parseInt(scoreText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Total Score must be a number.");
            return;
        }

        if (score < 0 || score > 200) {
            JOptionPane.showMessageDialog(this, "Total Score must be between 0 and 200.");
            return;
        }

        for (Round r : GolfClub.getRounds()) {
            if (r.getRoundId().equalsIgnoreCase(roundId)) {
                JOptionPane.showMessageDialog(this, "Duplicate Round ID. Please use a unique ID.");
                return;
            }
        }

        Round newRound = new Round(roundId, golferId, course, date, score);
        GolfClub.addRound(newRound);
        RecentRoundQueue.addRound(newRound);

        loadRoundsToTable();

        txtRoundId.setText("");
        txtRoundGolferId.setText("");
        txtCourseName.setText("");
        txtRoundDate.setText("");
        txtTotalScore.setText("");

        JOptionPane.showMessageDialog(this, "Round added successfully!");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoundActionPerformed

    private void btnDeleteRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoundActionPerformed
        int selectedRow = tblRounds.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a round to delete.");
            return;
        }

        GolfClub.removeRound(selectedRow);
        loadRoundsToTable();
        JOptionPane.showMessageDialog(this, "Round deleted successfully.");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoundView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRound;
    private javax.swing.JButton btnDeleteRound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblRounds;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtRoundDate;
    private javax.swing.JTextField txtRoundGolferId;
    private javax.swing.JTextField txtRoundId;
    private javax.swing.JTextField txtTotalScore;
    // End of variables declaration//GEN-END:variables
}
