/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package golfscorepro.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import golfscorepro.model.GolfClub;
import golfscorepro.model.Golfer;


/**
 *
 * @author upadh
 */
public class SearchSortView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchSortView.class.getName());

    /**
     * Creates new form SearchSortView
     */
    private void loadAllToTable() {
        DefaultTableModel model = (DefaultTableModel) tblResults.getModel();
        model.setRowCount(0);

        for (Golfer g : GolfClub.getGolfers()) {
            Object[] row = { g.getGolferId(), g.getName(), g.getHandicap() };
            model.addRow(row);
        }
    }

    public SearchSortView() {
        initComponents();
        loadAllToTable();
    }
    
    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Validation Error", JOptionPane.ERROR_MESSAGE);
    }

    private boolean isValidGolferIdFormat(String id) {
        // Simple rule: must not contain spaces, must be at least 2 chars
        if (id == null) return false;
        id = id.trim();
        if (id.length() < 2) return false;
        return !id.contains(" ");
    }


    private void bubbleSortByHandicapAsc() {
        int n = GolfClub.getGolfers().size();

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (GolfClub.getGolfers().get(j).getHandicap() >
                    GolfClub.getGolfers().get(j + 1).getHandicap()) {

                    Golfer temp = GolfClub.getGolfers().get(j);
                    GolfClub.getGolfers().set(j, GolfClub.getGolfers().get(j + 1));
                    GolfClub.getGolfers().set(j + 1, temp);
                }
            }
        }
    }
    
    private void bubbleSortByHandicapDesc() {
        int n = GolfClub.getGolfers().size();

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (GolfClub.getGolfers().get(j).getHandicap() <
                    GolfClub.getGolfers().get(j + 1).getHandicap()) {

                    Golfer temp = GolfClub.getGolfers().get(j);
                    GolfClub.getGolfers().set(j, GolfClub.getGolfers().get(j + 1));
                    GolfClub.getGolfers().set(j + 1, temp);
                }
            }
        }
    }
    
    private void bubbleSortById() {
        int n = GolfClub.getGolfers().size();

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (GolfClub.getGolfers().get(j).getGolferId()
                    .compareToIgnoreCase(GolfClub.getGolfers().get(j + 1).getGolferId()) > 0) {

                    Golfer temp = GolfClub.getGolfers().get(j);
                    GolfClub.getGolfers().set(j, GolfClub.getGolfers().get(j + 1));
                    GolfClub.getGolfers().set(j + 1, temp);
                }
            }
        }
    }
    
    private Golfer binarySearchById(String id) {
        int low = 0;
        int high = GolfClub.getGolfers().size() - 1;

        while (low <= high) {
            int mid = (low + high) / 2;
            Golfer g = GolfClub.getGolfers().get(mid);
            int result = g.getGolferId().compareToIgnoreCase(id);

            if (result == 0) return g;
            else if (result < 0) low = mid + 1;
            else high = mid - 1;
        }
        return null;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchId = new javax.swing.JTextField();
        btnSearchId = new javax.swing.JButton();
        btnSortAsc = new javax.swing.JButton();
        btnSortDesc = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search and Sort Golfers");

        tblResults.setBackground(new java.awt.Color(0, 151, 45));
        tblResults.setForeground(new java.awt.Color(255, 255, 255));
        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Golfer ID", "Name", "Handicap"
            }
        ));
        jScrollPane1.setViewportView(tblResults);

        jLabel1.setText("Search Name");

        jButton1.setBackground(new java.awt.Color(27, 94, 32));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search by Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search ID");

        btnSearchId.setBackground(new java.awt.Color(27, 94, 32));
        btnSearchId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchId.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchId.setText("Search by ID");
        btnSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIdActionPerformed(evt);
            }
        });

        btnSortAsc.setBackground(new java.awt.Color(27, 94, 32));
        btnSortAsc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSortAsc.setForeground(new java.awt.Color(255, 255, 255));
        btnSortAsc.setText("Sort by Ascending");
        btnSortAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortAscActionPerformed(evt);
            }
        });

        btnSortDesc.setBackground(new java.awt.Color(27, 94, 32));
        btnSortDesc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSortDesc.setForeground(new java.awt.Color(255, 255, 255));
        btnSortDesc.setText("Sort by Descending");
        btnSortDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortDescActionPerformed(evt);
            }
        });

        btnShowAll.setBackground(new java.awt.Color(27, 94, 32));
        btnShowAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnShowAll.setForeground(new java.awt.Color(255, 255, 255));
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(27, 94, 32));
        panelHeader.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnShowAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSortDesc)
                            .addComponent(btnSortAsc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnSearchId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchId)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnSortAsc)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSortDesc)))))
                .addGap(18, 18, 18)
                .addComponent(btnShowAll)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        if (GolfClub.getGolfers().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No golfers to display yet.");
            return;
        }
        loadAllToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String keyword = txtSearchName.getText().trim();

        if (keyword.isEmpty()) {
            showError("Please enter a name to search.");
            return;
        }

        if (keyword.length() < 2) {
            showError("Please enter at least 2 characters for name search.");
            return;
        }

        keyword = keyword.toLowerCase();

        DefaultTableModel model = (DefaultTableModel) tblResults.getModel();
        model.setRowCount(0);

        int count = 0;
        for (Golfer g : GolfClub.getGolfers()) {
            if (g.getName().toLowerCase().contains(keyword)) {
                Object[] row = { g.getGolferId(), g.getName(), g.getHandicap() };
                model.addRow(row);
                count++;
            }
        }

        if (count == 0) {
            JOptionPane.showMessageDialog(this, "No golfers found for: " + txtSearchName.getText().trim());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSortAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortAscActionPerformed
        if (GolfClub.getGolfers().isEmpty()) {
            showError("No golfers available to sort.");
        return;
        }
        bubbleSortByHandicapAsc();
        loadAllToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortAscActionPerformed

    private void btnSortDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortDescActionPerformed
        if (GolfClub.getGolfers().isEmpty()) {
            showError("No golfers available to sort.");
            return;
        }
        bubbleSortByHandicapDesc();
        loadAllToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortDescActionPerformed

    private void btnSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIdActionPerformed
        String id = txtSearchId.getText().trim();

        if (id.isEmpty()) {
            showError("Please enter a Golfer ID to search.");
            return;
        }

       

        if (GolfClub.getGolfers().isEmpty()) {
            showError("No golfers available to search.");
            return;
        }

        bubbleSortById(); // MUST sort before binary search
        Golfer result = binarySearchById(id);

        DefaultTableModel model = (DefaultTableModel) tblResults.getModel();
        model.setRowCount(0);

        if (result != null) {
            Object[] row = { result.getGolferId(), result.getName(), result.getHandicap() };
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Golfer ID not found: " + id);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchSortView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchId;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnSortAsc;
    private javax.swing.JButton btnSortDesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtSearchId;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
